title: Remember who you promised to be.
description: A place for my notes and thoughts, The saddest thing is forgetting who you promised to become.
theme: minima

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
